server:
  port: 80

spring:
  application:
    name: cloud-comsumer-order

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://www.eureka7002.com:7002/eureka/
      #      defaultZone: http://eureka7001.com:7001/eureka/
      #defaultZone: http://localhost:7001/eureka/
    #表示是否将自己注册进urekaserver默认为true
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true，才能配合ribbon使用负载均衡
    fetch-registry: true

#  instance:
#    ip-address: 127.0.0.1
#    instance-id: payment8001
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2