server:
  port: 80

eureka:
  client:
    service-url:
      #defaultZone: http://www.eureka7001.com:7001/eureka/
      defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7002.com:7002/eureka/
    register-with-eureka: false
spring:
  application:
    name: cloud-comsumer-order


feign:
  hystrix:
    enabled: true  #在feign中开启hystrix