server:
  port: 7001

spring:
  application:
    name: cloud-eureka-server7001

eureka:
  instance:
    #hostname: www.eureka7001.com
    hostname: www.eureka7001.com #eureka服务端实例名称
  client:
    fetch-registry: false  #不注册自己
    register-with-eureka: false # 不检索自己
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://www.eureka7002.com:7002/eureka/
#  server:
#    #关闭自我保护机制，保证不可用服务立即被踢出
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000